from datetime import datetime, timezone

from sqlalchemy import Boolean, CheckConstraint, Column, DateTime, ForeignKey, Index, Integer, String, Text, UniqueConstraint, text
from sqlalchemy.orm import DeclarativeBase


def utcnow():
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


def _model(name, table, *columns, table_args=()):
    attrs = {"__tablename__": table, "id": Column(Integer, primary_key=True), "created_at": Column(DateTime(timezone=True), default=utcnow, nullable=False)}
    attrs.update({column.name: column for column in columns})
    if table_args:
        attrs["__table_args__"] = table_args
    return type(name, (Base,), attrs)


ConfigurationReference = _model("ConfigurationReference", "configuration_reference", Column("scope", String(100), unique=True, nullable=False), Column("reference_kind", String(100), nullable=False), Column("reference_value", String(255), nullable=False))
SourceRecord = _model("SourceRecord", "source_record", Column("source_type", String(50), nullable=False), Column("source_system_scope", String(100), nullable=False), Column("stable_external_id", String(255)), Column("source_timestamp", DateTime(timezone=True)), Column("ingested_at", DateTime(timezone=True), default=utcnow, nullable=False), Column("retention_state", String(30), default="active", nullable=False), Column("deleted_or_redacted_at", DateTime(timezone=True)), Column("redaction_reason", String(255)), Column("manual_entry", Boolean, default=False, nullable=False), Column("provenance", String(255), default="system", nullable=False), table_args=(UniqueConstraint("source_system_scope", "stable_external_id"),))
SourceObservation = _model("SourceObservation", "source_observation", Column("source_record_id", Integer, ForeignKey("source_record.id"), nullable=False), Column("observed_at", DateTime(timezone=True), default=utcnow, nullable=False), Column("source_version_marker", String(255)), Column("observed_state", String(30), nullable=False), Column("outcome", String(50), nullable=False), Column("provenance", String(255), default="system", nullable=False), table_args=(UniqueConstraint("source_record_id", "source_version_marker"),))
SynchronizationCheckpoint = _model("SynchronizationCheckpoint", "synchronization_checkpoint", Column("source_system_scope", String(100), unique=True, nullable=False), Column("checkpoint_marker", String(255)), Column("last_success_at", DateTime(timezone=True)), Column("last_outcome", String(50), default="pending", nullable=False), Column("updated_at", DateTime(timezone=True), default=utcnow, nullable=False))
IdempotencyIdentity = _model("IdempotencyIdentity", "idempotency_identity", Column("operation_kind", String(100), nullable=False), Column("scope", String(100), nullable=False), Column("identity_key", String(255), nullable=False), Column("source_record_id", Integer, ForeignKey("source_record.id")), Column("target_reference", String(255)), Column("resolved_at", DateTime(timezone=True)), table_args=(UniqueConstraint("operation_kind", "scope", "identity_key"),))
Conversation = _model("Conversation", "conversation", Column("provenance", String(255), default="system", nullable=False), Column("superseded_at", DateTime(timezone=True)))
ConversationMembership = _model("ConversationMembership", "conversation_membership", Column("conversation_id", Integer, ForeignKey("conversation.id"), nullable=False), Column("source_record_id", Integer, ForeignKey("source_record.id"), unique=True, nullable=False), Column("evidence_type", String(50), nullable=False), Column("evidence_reference", String(255), nullable=False))
ManualNote = _model("ManualNote", "manual_note", Column("source_record_id", Integer, ForeignKey("source_record.id"), unique=True, nullable=False), Column("original_text", Text, nullable=False), Column("entered_at", DateTime(timezone=True), default=utcnow, nullable=False), Column("provenance", String(255), default="manual", nullable=False))
WhatsAppImport = _model("WhatsAppImport", "whatsapp_import", Column("source_record_id", Integer, ForeignKey("source_record.id"), unique=True, nullable=False), Column("original_text", Text, nullable=False), Column("pasted_at", DateTime(timezone=True), default=utcnow, nullable=False), Column("provenance", String(255), default="manual", nullable=False))
CalendarEventRepresentation = _model("CalendarEventRepresentation", "calendar_event_representation", Column("source_record_id", Integer, ForeignKey("source_record.id"), unique=True, nullable=False), Column("calendar_event_id", String(255), nullable=False), Column("starts_at", DateTime(timezone=True)), Column("ends_at", DateTime(timezone=True)), Column("current_state", String(30), default="active", nullable=False), Column("updated_at", DateTime(timezone=True), default=utcnow, nullable=False))
Activity = _model("Activity", "activity", Column("activity_type", String(50), nullable=False), Column("occurred_at", DateTime(timezone=True)), Column("description_reference", String(255)), Column("provenance", String(255), default="system", nullable=False))
ActivitySourceLink = _model("ActivitySourceLink", "activity_source_link", Column("activity_id", Integer, ForeignKey("activity.id"), nullable=False), Column("source_record_id", Integer, ForeignKey("source_record.id"), nullable=False), Column("link_purpose", String(100), nullable=False), table_args=(UniqueConstraint("activity_id", "source_record_id", "link_purpose"),))
CRMReference = _model("CRMReference", "crm_reference", Column("entity_type", String(50), nullable=False), Column("external_id", String(255), nullable=False), Column("display_reference", String(255)), Column("provenance", String(255), default="system", nullable=False), table_args=(UniqueConstraint("entity_type", "external_id"),))
CRMContextLink = _model("CRMContextLink", "crm_context_link", Column("crm_reference_id", Integer, ForeignKey("crm_reference.id"), nullable=False), Column("assistant_record_type", String(50), nullable=False), Column("assistant_record_id", Integer, nullable=False), Column("relationship_purpose", String(100), nullable=False), Column("confirmation_state", String(20), default="ambiguous", nullable=False), Column("confirmed_at", DateTime(timezone=True)), Column("provenance", String(255), default="system", nullable=False), table_args=(CheckConstraint("confirmation_state IN ('ambiguous', 'proposed', 'confirmed')"), CheckConstraint("(confirmation_state = 'confirmed' AND confirmed_at IS NOT NULL) OR (confirmation_state != 'confirmed' AND confirmed_at IS NULL)")))
IdentityLink = _model("IdentityLink", "identity_link", Column("identity_type", String(50), nullable=False), Column("identity_value", String(255), nullable=False), Column("crm_reference_id", Integer, ForeignKey("crm_reference.id"), nullable=False), Column("status", String(30), default="confirmed", nullable=False), Column("confirmed_at", DateTime(timezone=True), default=utcnow, nullable=False), Column("provenance", String(255), default="user", nullable=False), Column("superseded_at", DateTime(timezone=True)), table_args=(Index("uq_identity_link_active_confirmed", "identity_type", "identity_value", unique=True, sqlite_where=text("status = 'confirmed' AND superseded_at IS NULL")),))
IdentityLinkCorrection = _model("IdentityLinkCorrection", "identity_link_correction", Column("prior_identity_link_id", Integer, ForeignKey("identity_link.id"), unique=True, nullable=False), Column("replacement_identity_link_id", Integer, ForeignKey("identity_link.id"), nullable=False), Column("corrected_at", DateTime(timezone=True), default=utcnow, nullable=False), Column("provenance", String(255), default="user", nullable=False), table_args=(CheckConstraint("prior_identity_link_id != replacement_identity_link_id"),))
ExtractedFact = _model("ExtractedFact", "extracted_fact", Column("fact_type", String(100), nullable=False), Column("value_reference", String(255), nullable=False), Column("provenance", String(255), nullable=False), Column("superseded_at", DateTime(timezone=True)))
Inference = _model("Inference", "inference", Column("inference_type", String(100), nullable=False), Column("value_reference", String(255), nullable=False), Column("provenance", String(255), nullable=False), Column("confirmed_at", DateTime(timezone=True)))
Proposal = _model("Proposal", "proposal", Column("proposal_type", String(100), nullable=False), Column("value_reference", String(255), nullable=False), Column("provenance", String(255), nullable=False), Column("status", String(30), default="proposed", nullable=False))
FactSourceEvidence = _model("FactSourceEvidence", "fact_source_evidence", Column("extracted_fact_id", Integer, ForeignKey("extracted_fact.id"), nullable=False), Column("source_record_id", Integer, ForeignKey("source_record.id"), nullable=False), Column("evidence_reference", String(255), nullable=False), table_args=(UniqueConstraint("extracted_fact_id", "source_record_id", "evidence_reference"),))
InferenceSupport = _model("InferenceSupport", "inference_support", Column("inference_id", Integer, ForeignKey("inference.id"), nullable=False), Column("support_type", String(30), nullable=False), Column("support_id", Integer, nullable=False), table_args=(UniqueConstraint("inference_id", "support_type", "support_id"), CheckConstraint("support_type IN ('source', 'fact', 'inference')")))
ProposalSupport = _model("ProposalSupport", "proposal_support", Column("proposal_id", Integer, ForeignKey("proposal.id"), nullable=False), Column("support_type", String(30), nullable=False), Column("support_id", Integer, nullable=False), table_args=(UniqueConstraint("proposal_id", "support_type", "support_id"), CheckConstraint("support_type IN ('source', 'fact', 'inference', 'proposal')")))
AuditEvent = _model("AuditEvent", "audit_event", Column("event_type", String(100), nullable=False), Column("affected_record_type", String(50), nullable=False), Column("affected_record_id", Integer, nullable=False), Column("actor_or_source", String(100), nullable=False), Column("occurred_at", DateTime(timezone=True), default=utcnow, nullable=False), Column("provenance", String(255), nullable=False), Column("outcome_reference", String(255)), Column("failure_code", String(100)))
